### ISSUE TITLE
Problem with 7z on mac

### ISSUE THREAD

**Issue by yuters** [socketubs/Sublimall#12]
I've installed sublimall via Package Control
I'm always getting this message on mavericks:

![screen shot 2014-02-14 at 8 49 50 pm](https://f.cloud.github.com/assets/801718/2176934/1f793cd0-95e9-11e3-9ff1-79e1876a1de2.png)

I've tried installing it with:
`brew install p7zip`

It still didn't work so I tried adding the path in the sublimall settings:

```
// 7zip binary path (Sublimall will try to find it itself)
"7za_path": "/usr/local/Cellar/p7zip/9.20.1/bin/7za"
```

And I'm still getting the same error message has linked above, which is kinda harsh by the way, "Install it."

**Comment by jgacuca567** [comment]
@socketubs What is the Solution for OS X El Capitan
Current Version of Sublime `Stable Channel Build 3083`

**Comment by dotKev** [comment]
Ditto on request for OS X El Capitan.
Current version is Stable Channel, Build 3083

**Comment by socketubs** [comment]
Sorry guys I don't have Mac so it's difficult to help you.
Nothing in SublimeText console or in your `~/.sublimall.log` ?

**Comment by jgacuca567** [comment]
I am also experiencing the same issue on El Capitan Build 3083 on Mac as
well
On Fri, Dec 4, 2015 at 03:03 Geoffrey Lehée <notifications@github.com>
wrote:

> Sorry guys I don't have Mac so it's difficult to help you.
> Nothing in SublimeText console or in your ~/.sublimall.log ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/socketubs/Sublimall/issues/12#issuecomment-161904030>.
>
-- 
James Gacuca
jgacuca@gmail.com
(202)-569-1159

**Comment by jgacuca567** [comment]
@socketubs , How do I show you my log file?
