### ISSUE TITLE
Can't import get_7za_bin()

### ISSUE THREAD

**Issue by natecox** [socketubs/Sublimall#49]
I've recently run into an issue with sublimall that prevents me from uploading or backing up. Loading Sublime Text 3 gives me this issue in the console: 

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 157, in on_api_ready
    m.plugin_loaded()
  File "Sublimall in /home/tsuujin/.config/sublime-text-3/Installed Packages/Sublimall.sublime-package", line 16, in plugin_loaded
ImportError: cannot import name get_7za_bin
```

I've checked the package file, and the utils file that the `get_7za_bin` exists in is available, so I'm not sure why it wouldn't work. Furthermore, this install did work at one point. I'm not sure what would have changed, but it certainly doesn't load now.

**Comment by jgacuca567** [comment]
@socketubs  I keep getting this error "Sublimall needs 7zip to compress and encrypt "
            "your configuration.\n"
            "Please install it and specify its path in the settings file."), everytime I open Sublime. What is it that I am missing. Is it a 7-Zip Plugin or?
