### ISSUE TITLE
http://sublimall.org/ is down

### ISSUE THREAD

**Issue by JohnPoison** [socketubs/Sublimall#88]
can't read docs or even send the feedback email

**Comment by socketubs** [comment]
Hi,

As you can read in [README.md](https://github.com/socketubs/Sublimall/blob/master/README.md#sublimall), Sublimall is no long maintained, then website goes down.
But hopefully you can install [sublimall-server](https://github.com/socketubs/sublimall-server) by yourself.

And you can find raw html of doc page [here](https://github.com/socketubs/sublimall-server/blob/master/templates/docs.html).
