### ISSUE TITLE
I can't find a place to regist my account

### ISSUE THREAD

**Issue by gamelife1314** [socketubs/Sublimall#92]
I can't find a place to regist my account. Please tell what I should do step by step.

**Comment by socketubs** [comment]
First step: read project [README](https://github.com/socketubs/Sublimall#sublimall) :smile: 

> **Warning**: For people who saw Sublimall in trending, you have to know that I stop maintaining this project. But plugin and server source code are on github and maintainers are welcome!

**Comment by gamelife1314** [comment]
I need to build a server?

**Comment by socketubs** [comment]
Absolutely! You can find more information [here](https://github.com/socketubs/sublimall-server).
